language: node_js
node_js:
  - 'stable'

cache:
  dependencies:
    node_modules

script:
    - npm install
    - npm run test
    - npm run build

deploy:
  provider: surge
  skip cleanup: true
  domain: burly-reading.surge.sh
  project: ./build/

on:
  branch: master